---
networks:
  secure:
    driver: bridge
    external: true

services:
  adminer:
    image: ${DOCKER_IMAGE?}:${DOCKER_IMAGE_TAG?}
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - secure
    command:
      [
        "php",
        "-d",
        "memory_limit=${ADMINER_MEMORY_LIMIT}",
        "-d",
        "upload_max_filesize=${ADMINER_UPLOAD_MAX_FILESIZE}",
        "-d",
        "post_max_size=${ADMINER_POST_MAX_SIZE}",
        "-d",
        "max_execution_time=${ADMINER_MAX_EXECUTION_TIME}",
        "-S",
        "[::]:8080",
        "-t",
        "/var/www/html",
      ]
