---
networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true

services:
  adminer:
    image: ${DOCKER_IMAGE?}:${DOCKER_IMAGE_TAG?}
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - proxy
      - secure
